language: node_js
node_js:
- '6'
before_install:
- npm install -g typescript
- npm install -g typings
- npm install -g webpack
- npm install --only=dev
jobs:
  include:
    - stage: build application
      script: npm run build
    - stage: deploy to heroku
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_AUTH_KEY
        app: web-blackjack-game
        on:
          repo: Nevaan/web-blackjack