language: node_js
node_js:
- "6"
before_install:
- npm install -g typescript
- npm install -g grunt-cli
- npm install -g bower
- npm install -g typings
- typings install dt~jasmine --save --global
script:
- grunt build
